defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# basic params
cuda: false     # override to manually disable cuda, otherwise will use gpu if available (silently switches to cpu if not)
random_seed: 42
model_dir: outputs
data_file: matches.csv
split: 0.2  # train/valid split
task: full

# model params
model: mlp
nonlin: relu
num_layers: 1
dropout: 0
rnn_out: hidden
rnn_dropout: False
rnn_type: gru
rnn_bidir: False

# dict params
tokenizer: re

# training params
valid_every_n: 1
bs: 128  # bigger batches are more hardware-efficient
num_epochs: 25
num_feats: 18  # should be set based on the task: 18 for full, 37 for extended
edim: 16
hdim: 32
weight_classes: true  # probably need true, dataset fairly imbalanced
pos_weight_mod: 1.0  # hard to justify anything other than 1 here

# optimizer params
scheduler: plateau
optim: adam
lr: 0.001
weight_decay: 5e-4
momentum: 0.95