#!/usr/bin/python3

howell_raw_fields = [
	'token_name',
	'emps_li_0719',
	'emps_web_0719',
	'github_mainrep_commits_0719',
	'github_date_last_commit_0719',
	'github_repositories_0719',
	'github_mainrep_branches_0719',
	'github_mainrep_releases_0719',
	'github_mainrep_contributors_0719',
	'emps_0719',
	'github_mainrep_commits_thou_0719',
	'github_indicator_0719',
	'github_dayslastcommit_to_071019',
	'github_dayslastcommit_to_071019h',
	'raised_usd_mill',
	'whitepaper',
	'start_date_final',
	'symbol',
	'first_date_trading',
	'last_date_trading',
	'website',
	'linkedin_name',
	'linkedin_url',
	'company_name',
	'sector',
	'goal_to_raise_units',
	'founder_name',
	'founder_title',
	'founder_gender',
	'founder_source',
	'notes',
	'usdraised',
	'ico_failed',
	'utility',
	'eth_blockchain',
	'goal_to_raise',
	'goal_to_raise_usd',
	'country1',
	'country2',
	'country3',
	'country4',
	'website_new_research',
	'num_emps_website_incomplete',
	'github_mainrep_commits',
	'telegram_members',
	'twitter_followers',
	'telegram_indicator',
	'twitter_indicator',
	'github_indicator',
	'github_date_last_commit',
	'cancelledornoicoordoubleis',
	'new_blockchain',
	'blockchain',
	'cap_amt_crypto',
	'cap_amt_crypto_units',
	'currencies_accepted',
	'token_limit',
	'max_supply',
	'code_github',
	'pricing_approach',
	'description',
	'white_paper',
	'founder_name2',
	'founder2_title',
	'founder2_gender',
	'founder2_bckgr_crypto',
	'founder2_bckgr_finance',
	'founder2_bckgr_compsciIT',
	'founder2_bckgr_entrep',
	'end_date',
	'raised',
	'total_supply',
	'number_tokens_sold',
	'fraction_tokens_sold',
	'num_currencies_accepted',
	'blockchain_eth',
	'blockchain_waves',
	'blockchain_bitshares',
	'duration',
	'no_website',
	'sector_n',
	'circulating_supply',
	'fraction_tokens_sold_all',
	'raised_usd_mill_noair',
	'sector_s',
	'no_trading_data',
	'quarter_started_trading',
	'month_started_trading',
	'week_started_trading',
	'days_to_list',
	'circ_supply_all',
	'log_raised_usd_mill',
	'original_data_flag',
	'new845_data_flag',
	'name',
	'available_supply',
	'end_date_tokendata',
	'trade_length',
	'sector_s_old',
	'sector_agg_old',
	'sector_agg_n_old',
	'sector_agg',
	'ads',
	'data',
	'enterp',
	'newblockchain',
	'pay',
	'token',
	'trading',
	'asset',
	'gaming',
	'btc_prc_change',
	'etc_prc_change',
	'bch_prc_change',
	'prc_btc',
	'num_emps2',
	'num_emps_linkedin_wm',
	'num_emps2_wm',
	'year_trading_date',
	'month_trading_date',
	'quarter_trading_date',
	'week_trading_date',
	'month_year_trading_date',
	'quarter_year_trading_date',
	'week_year_trading_date',
	'quarter_year_all',
	'week_year_all',
	'year_all',
	'quarter_all',
	'completed',
	'btc_price_thou',
	'commercialization_new',
	'listed_original',
	'one_per_token',
	'dup',
	'num_emps_linkedin',
	'num_emps_website',
	'neg_log_amihud_d7',
	'log_avg_dvol_d7',
	'log_ab_ret_btc_d7',
	'log_turnover_d7',
	'log_volatility1_d7',
	'neg_log_amihud_d28',
	'log_avg_dvol_d28',
	'log_ab_ret_btc_d28',
	'log_turnover_d28',
	'log_volatility1_d28',
	'neg_log_amihud_d112',
	'log_avg_dvol_d112',
	'log_ab_ret_btc_d112',
	'log_turnover_d112',
	'log_volatility1_d112',
	'neg_log_amihud_d140',
	'log_ab_ret_btc_d140',
	'log_turnover_d140',
	'log_volatility1_d140',
	'neg_log_amihud_d168',
	'log_avg_dvol_d168',
	'log_ab_ret_btc_d168',
	'log_turnover_d168',
	'log_volatility1_d168',
	'amihud_d7',
	'amihud_d28',
	'amihud_d112',
	'amihud_d140',
	'amihud_d168',
	'amihud_log_d7',
	'amihud_log_d28',
	'amihud_log_d112',
	'amihud_log_d140',
	'amihud_log_d168',
	'turnover_d7',
	'turnover_d28',
	'turnover_d112',
	'turnover_d140',
	'turnover_d168',
	'avg_dvol_d7',
	'avg_dvol_d28',
	'avg_dvol_d112',
	'avg_dvol_d140',
	'avg_dvol_d168',
	'volatility1_d7',
	'volatility1_d28',
	'volatility1_d112',
	'volatility1_d140',
	'volatility1_d168',
	'volatility2_d7',
	'volatility2_d28',
	'volatility2_d112',
	'volatility2_d140',
	'volatility2_d168',
	'cret_d7',
	'cret_d28',
	'cret_d112',
	'cret_d140',
	'cret_d168',
	'amihud_log_rank_d7',
	'amihud_log_rank_d28',
	'amihud_log_rank_d112',
	'amihud_log_rank_d140',
	'amihud_log_rank_d168',
	'turnover_rank_d7',
	'turnover_rank_d28',
	'turnover_rank_d112',
	'turnover_rank_d140',
	'turnover_rank_d168',
	'avg_dvol_rank_d7',
	'avg_dvol_rank_d28',
	'avg_dvol_rank_d112',
	'avg_dvol_rank_d140',
	'avg_dvol_rank_d168',
	'rank_liq_measure_d7',
	'rank_liq_measure_d28',
	'rank_liq_measure_d112',
	'rank_liq_measure_d140',
	'rank_liq_measure_d168',
	'ret_eth_d7',
	'ret_eth_d28',
	'ret_eth_d112',
	'ret_eth_d140',
	'ret_eth_d168',
	'ret_btc_d7',
	'ret_btc_d28',
	'ret_btc_d112',
	'ret_btc_d140',
	'ret_btc_d168',
	'ret_btc_eth_d7',
	'ret_btc_eth_d28',
	'ret_btc_eth_d112',
	'ret_btc_eth_d140',
	'ret_btc_eth_d168',
	'log_avg_dvol_d140',
	'listed',
	'issuer_failed_new',
	'commercialization',
	'log_num_emps2_wm',
	'white_paper_final',
	'incentive_set_aside',
	'vesting',
	'budget',
	'VC',
	'founder_male',
	'founder_bckgr_crypto',
	'founder_bckgr_finance',
	'founder_bckgr_compsciIT',
	'founder_bckgr_entrep',
	'sector_agg_n',
	'country_usa',
	'country_china',
	'country_canada',
	'country_russia',
	'country_singapore',
	'country_switzerland',
	'country_israel',
	'country_uk',
	'country_hk',
	'country_dispersed',
	'telegram_members_thou',
	'twitter_followers_thou',
	'github_repositories',
	'github_mainrep_commits_thou',
	'github_mainrep_branches',
	'github_mainrep_releases',
	'github_mainrep_contributors',
	'github_dayslastcommit_toApr11',
	'capped',
	'barred_to_us',
	'presale',
	'airdrop',
	'pricing_dynamic',
	'pricing_sensitive',
	'pricing_auction',
	'future_token_creation',
	'curr_accept_usd',
	'curr_accept_eur',
	'curr_accept_btc',
	'curr_accept_eth',
	'curr_accept_xrp',
	'curr_accept_ltc',
	'curr_accept_waves',
	'had_goal_to_raise',
	'goal_to_raise_usd_mill',
	'raised_less_goal',
	'ind_raised_less_goal',
	'met_goal',
	'github_dayslast_toApr11_100',
	'month_all',
	'emps_0719_wm',
	'log_emps_0719_wm',
	'emps_delta',
	'github_mainrep_branches_1000',
	'github_dayslastcommit_toApr11_30',
	'github_mainrep_contributors_1000',
	'github_mainrep_releases_1000',
	'github_repositories_1000',
	'github_mainrep_br_0719_1000',
	'github_dayslastcommto_71019_30',
	'github_mainrep_cont_0719_1000',
	'github_mainrep_rel_0719_1000',
	'github_repos_0719_1000',
	'github_br_delta',
	'github_cont_delta',
	'github_rel_delta',
	'github_rep_delta',
	'github_commits_delta',
	'high_price_1',
	'high_btc_price',
	'med_btc_price',
	'low_btc_price',
	'raised_usd_bill'
]




# fields we plan to use
howell_fields = [
	'token_name',
	'github_repositories_0719',
	'github_indicator_0719',
	'whitepaper',
	'start_date_final',
	'symbol',
	'first_date_trading',
	'website',
	'linkedin_name',
	'linkedin_url',
	'company_name',
	'sector',
	'goal_to_raise_units',
	'founder_name',
	'founder_title',
	'founder_gender',
	'founder_source',
	'notes',
	'ico_failed',
	'utility',
	'eth_blockchain',
	'country1',
	'country2',
	'country3',
	'country4',
	'website_new_research',
	'num_emps_website_incomplete',
	'github_mainrep_commits',
	'telegram_members',
	'twitter_followers',
	'telegram_indicator',
	'twitter_indicator',
	'github_indicator',
	'cancelledornoicoordoubleis',
	'new_blockchain',
	'blockchain',
	'cap_amt_crypto',
	'cap_amt_crypto_units',
	'currencies_accepted',
	'token_limit',
	'max_supply',
	'code_github',
	'white_paper',
	'founder_name2',
	'founder2_title',
	'founder2_gender',
	'founder2_bckgr_crypto',
	'founder2_bckgr_finance',
	'founder2_bckgr_compsciIT',
	'founder2_bckgr_entrep',
	'num_currencies_accepted',
	'blockchain_eth',
	'blockchain_waves',
	'blockchain_bitshares',
	'duration',
	'no_website',
	'sector_n',
	'sector_s',
	'no_trading_data',
	'quarter_started_trading',
	'month_started_trading',
	'week_started_trading',
	'days_to_list',
	'circ_supply_all',
	'original_data_flag',
	'new845_data_flag',
	'name',
	'available_supply',
	'trade_length',
	'sector_s_old',
	'sector_agg_old',
	'sector_agg_n_old',
	'sector_agg',
	'ads',
	'data',
	'enterp',
	'newblockchain',
	'pay',
	'token',
	'trading',
	'asset',
	'gaming',
	'num_emps2',
	'num_emps_linkedin_wm',
	'num_emps2_wm',
	'commercialization_new',
	'listed_original',
	'one_per_token',
	'dup',
	'num_emps_linkedin',
	'num_emps_website',
	'listed',
	'issuer_failed_new',
	'commercialization',
	'log_num_emps2_wm',
	'white_paper_final',
	'incentive_set_aside',
	'vesting',
	'budget',
	'VC',
	'founder_male',
	'founder_bckgr_crypto',
	'founder_bckgr_finance',
	'founder_bckgr_compsciIT',
	'founder_bckgr_entrep',
	'sector_agg_n',
	'country_usa',
	'country_china',
	'country_canada',
	'country_russia',
	'country_singapore',
	'country_switzerland',
	'country_israel',
	'country_uk',
	'country_hk',
	'country_dispersed',
	'github_repositories',
	'capped',
	'barred_to_us',
	'presale',
	'airdrop',
	'pricing_dynamic',
	'pricing_sensitive',
	'pricing_auction',
	'future_token_creation',
	'curr_accept_usd',
	'curr_accept_eur',
	'curr_accept_btc',
	'curr_accept_eth',
	'curr_accept_xrp',
	'curr_accept_ltc',
	'curr_accept_waves',
	'had_goal_to_raise',
	'ind_raised_less_goal',
	'met_goal'
]

"""
SAPKOTA FIELD DESCRIPTIONS

S.No.	Variables	Descriptions
1	Name	Name of the ICO
2	Raised($)	Raised amount in Dollar
3	Reason	Reason for the scam accusations
4	Year	Year of issuance
5	Type	Type of scam
6	PL		Page lenth of ICO whitepaper
7	WC		Word Count of whitepaper
8	WD		Word to page density
9	S.GI	Overall Psychological Sentiment (Harvard)
10	N.GI	Negative Psychological Sentiment (Harvard)
11	P.GI	Positive Psychological Sentiment (Harvard)
12	S.HE	Overall Henry Finance Sentiment
13	N.HE	Negative Henry Finance Sentiment
14	P.HE	Positive Henry Finance Sentiment
15	S.LM	Overall Loughrn Mc Donald sentiment
16	N.LM	Negative Loughrn Mc Donald sentiment
17	P.LM	Positive Loughrn Mc Donald sentiment
18	RU.LM	Risk Uncertainity Loughrn Mc Donald sentiment
19	S.QDAP	Overall discourse sentiment 
20	N.QDAP	Negative discourse sentiment 
21	P.QDAP	Positive discourse sentiment 
22	S.Score	Jaccard Similarity Score of whitepaper
23	Flesch	Readability Score Type1
24	Flesch.K	Readability Score Type2
25	RIX		Readability Score Type3
26	SMOG	Readability Score Type4
27	FOG		Readability Score Type5
28	ARI		Readability Score Type6
29	Col		Readability Score Type7
30	RScore	Disclosure of Risk (yes 1, 0 no)
31	NoC		Number of category ICO is registered under
32	Team	Disclosure of team (yes 1, 0 no)
33	C.Info	Disclosure of country (yes 1, 0 no)
34	KYC	KYC needed (yes 1, 0 no)
35	Twitter	Twitter account (yes 1, 0 no)
36	Video	Youtube account (yes 1, 0 no)
37	Miles	Disclosure of milestone (yes 1, 0 no)
38	SoftCap	Disclosure of soft capital (yes 1, 0 no)
39	HardCap	Disclosure of hard capital (yes 1, 0 no)
40	Tgram	Telegram account (yes 1, 0 no)
41	NoT		Disclosure of number of tokens (yes 1, 0 no)
"""

sapkota_raw_fields = [
	'Name',
	'Raised($)',
	'Reason',
	'Year',
	'Type',
	'PL',
	'WC',
	'WD',
	'S.GI',
	'N.GI',
	'P.GI',
	'S.HE',
	'N.HE',
	'P.HE',
	'S.LM',
	'N.LM',
	'P.LM',
	'RU.LM',
	'S.QDAP',
	'N.QDAP',
	'P.QDAP',
	'S.Score',
	'Flesch',
	'Flesch.K',
	'RIX',
	'SMOG',
	'FOG',
	'ARI',
	'Col',
	'RScore',
	'NoC',
	'Team',
	'C.Info',
	'KYC',
	'Twitter',
	'Video',
	'Miles',
	'SoftCap',
	'HardCap',
	'Tgram',
	'NoT'
]


sapkota_fields = [
	'Name',
	'Raised($)',
	'Reason',
	'Year',
	'Type',
	'PL',
	'WC',
	'WD',
	'RScore',
	'NoC',
	'Team',
	'C.Info',
	'KYC',
	'Twitter',
	'Video',
	'Miles',
	'SoftCap',
	'HardCap',
	'Tgram',
	'NoT'
]







